comment out duplicated stuff
keep it for the future

diff --git a/templates/default/puma-init.erb b/templates/default/puma-init.erb
--- a/templates/default/puma-init.erb
+++ b/templates/default/puma-init.erb
@@ -5,75 +5,74 @@
 
 # The script will start with config set by $PUMA_CONFIG_FILE by default
 
-PUMA_CONFIG_FILE=<%= @config_path %>
-PUMA_PID_FILE=<%= @pid_path %>
-PUMA_SOCKET=<%= @socket_path %>
-
-# check if puma process is running
-puma_is_running() {
-  if [ -S $PUMA_SOCKET ] ; then
-    if [ -e $PUMA_PID_FILE ] ; then
-      if cat $PUMA_PID_FILE | xargs pgrep -P > /dev/null ; then
-        return 0
-      else
-        echo "No puma process found"
-      fi
-    else
-      echo "No puma pid file found"
-    fi
-  else
-    echo "No puma socket found"
-  fi
-
-  return 1
-}
-
-case "$1" in
-  start)
-    echo "Starting puma..."
-    rm -f $PUMA_SOCKET
-    if [ -e $PUMA_CONFIG_FILE ] ; then
-      bundle exec puma --config $PUMA_CONFIG_FILE
-    else
-      bundle exec puma --daemon --bind unix://$PUMA_SOCKET --pidfile $PUMA_PID_FILE
-    fi
-
-    echo "done"
-    ;;
-
-  stop)
-    echo "Stopping puma..."
-      kill -s SIGTERM `cat $PUMA_PID_FILE`
-      rm -f $PUMA_PID_FILE
-      rm -f $PUMA_SOCKET
-
-    echo "done"
-    ;;
-
-  restart)
-    if puma_is_running ; then
-      echo "Hot-restarting puma..."
-      kill -s SIGUSR2 `cat $PUMA_PID_FILE`
-
-      echo "Doublechecking the process restart..."
-      sleep 5
-      if puma_is_running ; then
-        echo "done"
-        exit 0
-      else
-        echo "Puma restart failed :/"
-      fi
-    fi
-
-    echo "Trying cold reboot"
-    $0 start
-    ;;
-
-  *)
-    echo "Usage: script/puma.sh {start|stop|restart}" >&2
-    ;;
-esac
-
+#PUMA_CONFIG_FILE=/home/fanwars/projects/fanwars/shared/config/fanwars.rb
+#PUMA_PID_FILE=/home/fanwars/projects/fanwars/shared/pids/fanwars.pid
+#PUMA_SOCKET=/home/fanwars/projects/fanwars/shared/fanwars.sock
+#
+## check if puma process is running
+#puma_is_running() {
+#  if [ -S $PUMA_SOCKET ] ; then
+#    if [ -e $PUMA_PID_FILE ] ; then
+#      if cat $PUMA_PID_FILE | xargs pgrep -P > /dev/null ; then
+#        return 0
+#      else
+#        echo "No puma process found"
+#      fi
+#    else
+#      echo "No puma pid file found"
+#    fi
+#  else
+#    echo "No puma socket found"
+#  fi
+#
+#  return 1
+#}
+#
+#case "$1" in
+#  start)
+#    echo "Starting puma..."
+#    rm -f $PUMA_SOCKET
+#    if [ -e $PUMA_CONFIG_FILE ] ; then
+#      bundle exec puma --config $PUMA_CONFIG_FILE
+#    else
+#      bundle exec puma --daemon --bind unix://$PUMA_SOCKET --pidfile $PUMA_PID_FILE
+#    fi
+#
+#    echo "done"
+#    ;;
+#
+#  stop)
+#    echo "Stopping puma..."
+#      kill -s SIGTERM `cat $PUMA_PID_FILE`
+#      rm -f $PUMA_PID_FILE
+#      rm -f $PUMA_SOCKET
+#
+#    echo "done"
+#    ;;
+#
+#  restart)
+#    if puma_is_running ; then
+#      echo "Hot-restarting puma..."
+#      kill -s SIGUSR2 `cat $PUMA_PID_FILE`
+#
+#      echo "Doublechecking the process restart..."
+#      sleep 5
+#      if puma_is_running ; then
+#        echo "done"
+#        exit 0
+#      else
+#        echo "Puma restart failed :/"
+#      fi
+#    fi
+#
+#    echo "Trying cold reboot"
+#    script/puma.sh start
+#    ;;
+#
+#  *)
+#    echo "Usage: script/puma.sh {start|stop|restart}" >&2
+#    ;;
+#esac
 
 #!/bin/sh
 # BEGIN INIT INFO
